spring:
  redis:
    host: localhost
    port: 6379
    password:
    database: 15
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: session-service
          uri: http://localhost:8090/
          predicates:
            - Path=/test/**

server:
  port: 8080

logging:
  level:
    root: info

black-ip:
  ip-list: ## 支持模糊配置
    - 0:0:0:0:0:0:0:*



