#profiles:
#  active: dev

spring:
  main:
    allow-bean-definition-overriding: true
  redis:
    host: localhost
    port: 6379
    password:
    database: 15
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
  application:
    name: spring-cloud-gateway-app
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        namespace:
      discovery:
        server-add: localhost:8848
    gateway:
      routes:
        - id: session-service
          uri: http://localhost:8090/
          predicates:
            - Path=/test/**
    sentinel:
      enabled: true
      eager: true # 取消控制台懒加载，项目启动即连接Sentinel
      transport:
        port: 8082 # 本地客户端的端口
        dashboard: localhost:8081 # 控制台地址
      filter:
        enabled: false
#      datasource:
#        flow_ds:
#          nacos:
#            server-addr: localhost:8848
#            data-id: sentinel_provider_flow_rule
#            group-id: DEFAULT_GROUP
#            data-type: json
#            rule-type: flow


server:
  port: 8080

logging:
  level:
    root: info

black-ip:
  ip-list: ## 支持模糊配置
  #- 0:0:0:0:0:0:0:*

skip-url:
  url-List:
#  - /login/xxx
#  - /logout/xxx

jwt:
  secret:
    key: jwt-secret-key
    auth-token-key: userInfoKey
    auth-login-url: https://www.baidu.com





